// image-tool-meta.jsx
import { Layers3 } from "../vendor.js";
import { __jsx } from "../shared/jsx-runtime.js";
import { RotateIcon, Stamp } from "./package.jsx";
import {
  AnnotationIcon,
  MultiAngleIcon,
  PanoramaIcon,
  RelightIcon,
  StoryboardGridIcon,
} from "../canvas/fullscreen-icon.jsx";
import {
  ColorAdjustIcon,
  CropIcon,
  EraseIcon,
  OutpaintIcon,
  RedrawIcon,
  RemoveBgIcon,
  SuperResolutionIcon,
} from "../canvas/file-missing-icon.jsx";

export const IMAGE_TOOL_META = {
  erase: {
    id: "erase",
    labelKey: "canvas.erase",
    defaultLabel: "Erase",
    icon: <EraseIcon />,
    requiresDimensions: true,
  },
  redraw: {
    id: "redraw",
    labelKey: "canvas.redraw.label",
    defaultLabel: "Redraw",
    icon: <RedrawIcon />,
    requiresDimensions: true,
  },
  crop: {
    id: "crop",
    labelKey: "canvas.crop",
    defaultLabel: "Crop",
    icon: <CropIcon />,
    requiresDimensions: false,
  },
  outpaint: {
    id: "outpaint",
    labelKey: "canvas.outpaint",
    defaultLabel: "Outpaint",
    icon: <OutpaintIcon />,
    requiresDimensions: true,
  },
  "super-resolution": {
    id: "super-resolution",
    labelKey: "canvas.superResolution.label",
    defaultLabel: "HD",
    icon: <SuperResolutionIcon />,
    requiresDimensions: true,
  },
  "remove-bg": {
    id: "remove-bg",
    labelKey: "canvas.removeBg.label",
    defaultLabel: "Remove Background",
    icon: <RemoveBgIcon />,
    requiresDimensions: true,
    costToolId: "remove-bg",
  },
  "color-adjust": {
    id: "color-adjust",
    labelKey: "canvas.colorAdjust",
    defaultLabel: "Color Adjust",
    icon: <ColorAdjustIcon />,
    requiresDimensions: false,
  },
  "image-inplace-edit": {
    id: "image-inplace-edit",
    labelKey: "canvas.imageEdit.label",
    defaultLabel: "Edit Image",
    icon: <AnnotationIcon size={20} />,
    requiresDimensions: false,
  },
  rotate: {
    id: "rotate",
    labelKey: "canvas.rotate.label",
    defaultLabel: "Rotate",
    icon: <RotateIcon />,
    requiresDimensions: true,
  },
  "multi-angle": {
    id: "multi-angle",
    labelKey: "canvas.multiAngle",
    defaultLabel: "AnyAngle",
    icon: <MultiAngleIcon size={16} />,
    requiresDimensions: false,
    dataActionUiId: "canvas.node-multi-angle",
  },
  "storyboard-grid": {
    id: "storyboard-grid",
    labelKey: "canvas.storyboardGrid",
    defaultLabel: "Storyboard",
    icon: <StoryboardGridIcon />,
    requiresDimensions: false,
    dataActionUiId: "canvas.node-storyboard-grid",
  },
  "panorama-reference": {
    id: "panorama-reference",
    labelKey: "canvas.panorama.title",
    defaultLabel: "Panorama",
    icon: <PanoramaIcon />,
    requiresDimensions: false,
    dataActionUiId: "canvas.node-panorama-reference",
  },
  watermark: {
    id: "watermark",
    labelKey: "canvas.watermark.label",
    defaultLabel: "Watermark",
    icon: <Stamp size={20} strokeWidth={1.6} aria-hidden="true" />,
    requiresDimensions: false,
    dataActionUiId: "canvas.node-watermark",
  },
  relight: {
    id: "relight",
    labelKey: "canvas.relight",
    defaultLabel: "Relight",
    icon: <RelightIcon />,
    requiresDimensions: false,
    dataActionUiId: "canvas.node-relight",
  },
  "layer-decompose": {
    id: "layer-decompose",
    labelKey: "canvas.layerDecompose.label",
    defaultLabel: "图层拆分",
    icon: <Layers3 size={18} strokeWidth={1.5} aria-hidden="true" />,
    requiresDimensions: true,
    dataActionUiId: "canvas.node-layer-decompose",
  },
};
