// track-events.js
import { AUTH_TRACK_EVENTS } from "../vendor.js";

export const TRACK_EVENTS = {
  // App lifecycle
  APP_LAUNCH: "app_launch",
  APP_QUIT: "app_quit",
  APP_CRASH: "app_crash",
  APP_ERROR: "app_error",
  APP_MEMORY_WARNING: "app_memory_warning",
  APP_PERFORMANCE: "app_performance",
  MEDIA_REFERENCE_DIAGNOSTIC_RESULT: "media_reference_diagnostic_result",
  GPU_RECOVERY: "gpu_recovery",
  WORKSPACE_RETENTION_SAMPLE: "workspace_retention_sample",
  DATA_DIRECTORY_ACTIVATION: "data_directory_activation",
  DATA_DIRECTORY_FALLBACK_CREATE: "data_directory_fallback_create",
  DATA_DIRECTORY_RECOVERY: "data_directory_recovery",
  DATA_DIRECTORY_MIGRATION_BLOCKED: "data_directory_migration_blocked",
  RUM_INIT_STATUS: "rum_init_status",
  UPDATER_POLICY_BOOTSTRAP: "updater_policy_bootstrap",
  LEGACY_INSTALL_CENSUS_POLICY_EVALUATED:
    "legacy_install_census_policy_evaluated",
  LEGACY_INSTALL_DETECTED: "legacy_install_detected",
  // Auth
  ...AUTH_TRACK_EVENTS,
  // Team / request-and-billing Group recovery
  TEAM_GROUP_RECOVERY: "team_group_recovery",
  // WebSocket
  WS_CONNECT_START: "ws_connect_start",
  WS_CONNECT_SUCCESS: "ws_connect_success",
  WS_CONNECT_FAILED: "ws_connect_failed",
  WS_DISCONNECT: "ws_disconnect",
  WS_RECONNECT: "ws_reconnect",
  // Chat
  CHAT_SESSION_CREATE: "chat_session_create",
  CHAT_SESSION_SWITCH: "chat_session_switch",
  CHAT_MESSAGE_SEND: "chat_message_send",
  CHAT_MESSAGE_RECEIVED: "chat_message_received",
  CHAT_MESSAGE_FAILED: "chat_message_failed",
  /** Observe-only watchdog stall notice shown/recovered (`session_stalled` push). */
  CHAT_SESSION_STALLED: "chat_session_stalled",
  /** User decision on the stall banner: keep waiting (dismiss) or stop task. */
  CHAT_SESSION_STALL_ACTION: "chat_session_stall_action",
  /** Authoritative terminal outcome of a LoopGuard confirmation. */
  CHAT_LOOP_GUARD_SETTLED: "chat_loop_guard_settled",
  /** User interaction with the workspace chat composer toolbar. */
  CHAT_TOOLBAR_ACTION: "chat_toolbar_action",
  /** User explicitly stops the currently running agent turn. */
  CHAT_TASK_STOP: "chat_task_stop",
  /** User interaction with the workspace chat session tab strip. */
  CHAT_SESSION_TAB_ACTION: "chat_session_tab_action",
  /** User action on an http(s) link rendered inside a chat message. */
  CHAT_LINK_ACTION: "chat_link_action",
  // Upload
  UPLOAD_FILE_START: "upload_file_start",
  UPLOAD_FILE_SUCCESS: "upload_file_success",
  UPLOAD_FILE_FAILED: "upload_file_failed",
  // Generation tasks
  GENERATE_TASK_SUBMIT: "generate_task_submit",
  GENERATE_TASK_SUCCESS: "generate_task_success",
  GENERATE_TASK_FAILED: "generate_task_failed",
  GENERATE_TASK_CANCEL: "generate_task_cancel",
  MODEL_CATALOG_POLLING_POLICY_INVALID: "model_catalog_polling_policy_invalid",
  // MCP tools
  MCP_TOOL_CALL_START: "mcp_tool_call_start",
  MCP_TOOL_CALL_SUCCESS: "mcp_tool_call_success",
  MCP_TOOL_CALL_FAILED: "mcp_tool_call_failed",
  // Gateway HTTP
  GATEWAY_API_REQUEST: "gateway_api_request",
  GATEWAY_API_RESPONSE: "gateway_api_response",
  GATEWAY_API_FAILED: "gateway_api_failed",
  // Workspace
  WORKSPACE_CREATE: "workspace_create",
  WORKSPACE_OPEN: "workspace_open",
  WORKSPACE_CLOSE: "workspace_close",
  WORKSPACE_RESTORE_CIRCUIT_BREAKER: "workspace_restore_circuit_breaker",
  PROJECT_EXPORT_FAILED: "project_export_failed",
  PROJECT_IMPORT_RESULT: "project_import_result",
  HUB_ENTRY_LOAD_RESULT: "hub_entry_load_result",
  // Skills
  SKILL_INSTALL: "skill_install",
  SKILL_INSTALL_FAILED: "skill_install_failed",
  SKILL_UNINSTALL: "skill_uninstall",
  SKILL_UNINSTALL_FAILED: "skill_uninstall_failed",
  SKILL_TOGGLE: "skill_toggle",
  SKILL_INVOKE: "skill_invoke",
  // Skill market (browse / detail / acquisition funnel)
  SKILL_MARKET_OPEN: "skill_market_open",
  SKILL_DETAIL_VIEW: "skill_detail_view",
  SKILL_TRY: "skill_try",
  SKILL_EXPORT: "skill_export",
  SKILL_FORK: "skill_fork",
  SKILL_IMPORT: "skill_import",
  SKILL_IMPORT_FAILED: "skill_import_failed",
  SKILL_SEARCH: "skill_search",
  SKILL_FILTER: "skill_filter",
  SKILL_LOAD_MORE: "skill_load_more",
  SKILL_TAB_SWITCH: "skill_tab_switch",
  // Skill creator (user-authored skills)
  SKILL_CREATOR_INVOKE: "skill_creator_invoke",
  // Post-install activation funnel
  SKILL_DEBUG_OPEN: "skill_debug_open",
  // Home page (scene tags + curated query funnel)
  HOME_SCENE_TAG_CLICK: "home_scene_tag_click",
  HOME_SCENE_QUERY_SELECT: "home_scene_query_select",
  HOME_QUICK_START_CONFIG_RESOLUTION: "home_quick_start_config_resolution",
  HOME_MEDIA_SHOWCASE_CONFIG_RESOLUTION:
    "home_media_showcase_config_resolution",
  HOME_MEDIA_SHOWCASE_EXPOSURE: "home_media_showcase_exposure",
  HOME_MEDIA_SHOWCASE_TAB_EXPOSURE: "home_media_showcase_tab_exposure",
  HOME_MEDIA_SHOWCASE_TAB_SWITCH: "home_media_showcase_tab_switch",
  HOME_MEDIA_SHOWCASE_CONTENT_EXPOSURE: "home_media_showcase_content_exposure",
  HOME_MEDIA_SHOWCASE_CONTENT_CLICK: "home_media_showcase_content_click",
  HOME_WIDGET_VIEW: "home_widget_view",
  HOME_WIDGET_CLICK: "home_widget_click",
  HOME_WIDGET_DISMISS: "home_widget_dismiss",
  HOME_WIDGET_ACTION_FAILED: "home_widget_action_failed",
  // Settings
  SETTINGS_CHANGE: "settings_change",
  // 服务端编排弹窗(详见 modules/business/server-driven-popup)
  SERVER_DRIVEN_POPUP_VIEW: "server_driven_popup_view",
  SERVER_DRIVEN_POPUP_ACTION_CLICK: "server_driven_popup_action_click",
  SERVER_DRIVEN_POPUP_ACTION_FAILED: "server_driven_popup_action_failed",
  SERVER_DRIVEN_POPUP_DISMISS: "server_driven_popup_dismiss",
  // Onboarding (first-launch guide tour) — REMOVED: 4-step tour deprecated, replaced by
  // login-gate (auth.login-gate) + interest-selection (interestSelection) flow.
  // Login gate (启动强阻断登录弹窗)
  LOGIN_GATE_VIEW: "login_gate_view",
  LOGIN_GATE_DISMISS: "login_gate_dismiss",
  // Interest selection (登录后创作方向多选)
  INTEREST_SELECTION_VIEW: "interest_selection_view",
  INTEREST_SELECTION_COMPLETE: "interest_selection_complete",
  // Coach mark (in-app guided tips)
  COACH_MARK_SHOW: "coach_mark_show",
  COACH_MARK_DISMISS: "coach_mark_dismiss",
  // Plugin discovery → detail → install → canvas adoption → use funnel
  PLUGIN_CLICK: "plugin_click",
  PLUGIN_LIST_VIEW: "plugin_list_view",
  PLUGIN_DETAIL_VIEW: "plugin_detail_view",
  PLUGIN_INSTALL: "plugin_install",
  PLUGIN_INSTALL_FAILED: "plugin_install_failed",
  PLUGIN_UNINSTALL: "plugin_uninstall",
  PLUGIN_UNINSTALL_FAILED: "plugin_uninstall_failed",
  PLUGIN_ADD_TO_CANVAS: "plugin_add_to_canvas",
  PLUGIN_ADD_TO_CANVAS_FAILED: "plugin_add_to_canvas_failed",
  PLUGIN_EDITOR_OPEN: "plugin_editor_open",
  PLUGIN_WORKFLOW_CLICK: "plugin_workflow_click",
  PLUGIN_WORKFLOW_OPEN: "plugin_workflow_open",
  PLUGIN_WORKFLOW_OPEN_FAILED: "plugin_workflow_open_failed",
  PLUGIN_OUTPUT_CREATE: "plugin_output_create",
  // ComfyUI workflow catalogue, canvas binding and batch execution funnel.
  COMFYUI_WORKFLOW_CATALOG_ACTION: "comfyui_workflow_catalog_action",
  COMFYUI_WORKFLOW_INSTALL: "comfyui_workflow_install",
  COMFYUI_WORKFLOW_INSTALL_FAILED: "comfyui_workflow_install_failed",
  COMFYUI_WORKFLOW_OPEN: "comfyui_workflow_open",
  COMFYUI_WORKFLOW_OPEN_FAILED: "comfyui_workflow_open_failed",
  COMFYUI_WORKFLOW_DRAFT_ACTION: "comfyui_workflow_draft_action",
  // Updater
  APP_UPDATE_CHECK: "app_update_check",
  APP_UPDATE_DOWNLOAD: "app_update_download",
  APP_UPDATE_INSTALL: "app_update_install",
  APP_UPDATE_INSTALL_SAFETY_BLOCKED: "app_update_install_safety_blocked",
  APP_INSTALL_LOCATION: "app_install_location",
  UPDATER_FAILURE: "updater_failure",
  // Canvas
  CANVAS_OPEN: "canvas_open",
  CANVAS_RENDER_POLICY_APPLIED: "canvas_render_policy_applied",
  CANVAS_SURFACE_RECOVERY: "canvas_surface_recovery",
  CANVAS_NODE_ADD: "canvas_node_add",
  CANVAS_NODE_RUN: "canvas_node_run",
  CANVAS_EXPORT: "canvas_export",
  CANVAS_POPOVER_OPEN: "canvas_popover_open",
  CANVAS_GENERATE_SUBMIT: "canvas_generate_submit",
  // Canvas view enter
  CANVAS_VIEW_ENTER: "canvas_view_enter",
  CANVAS_STICKER_ADD: "canvas_sticker_add",
  CANVAS_ZOOM_CHANGE: "canvas_zoom_change",
  CANVAS_MINIMAP_TOGGLE: "canvas_minimap_toggle",
  CANVAS_EDGES_TOGGLE: "canvas_edges_toggle",
  // Canvas — generation outcome / satisfaction (proposal theme 1)
  CANVAS_NODE_REGENERATE: "canvas_node_regenerate",
  CANVAS_NODE_SAVE: "canvas_node_save",
  CANVAS_NODE_DELETE_AFTER_GENERATE: "canvas_node_delete_after_generate",
  CANVAS_NODE_TOOL_CLICK: "canvas_node_tool_click",
  CANVAS_NODE_TOOL_APPLY: "canvas_node_tool_apply",
  CANVAS_NODE_TOOL_ABANDON: "canvas_node_tool_abandon",
  CANVAS_GENERATE_ABANDON: "canvas_generate_abandon",
  // Canvas — common node interactions (proposal theme 2)
  CANVAS_NODE_COPY_PASTE: "canvas_node_copy_paste",
  CANVAS_UNDO_REDO: "canvas_undo_redo",
  CANVAS_CONTEXT_MENU_CLICK: "canvas_context_menu_click",
  CANVAS_SHORTCUT_USE: "canvas_shortcut_use",
  CANVAS_SELECTION_CHANGE: "canvas_selection_change",
  CANVAS_SIDEBAR_HOME_CLICK: "canvas_sidebar_home_click",
  CANVAS_SIDEBAR_TAB_CLICK: "canvas_sidebar_tab_click",
  // Canvas — pre-generate parameter selection (proposal theme 3)
  CANVAS_PARAM_ADJUST: "canvas_param_adjust",
  CANVAS_POPOVER_CLOSE_WITHOUT_SUBMIT: "canvas_popover_close_without_submit",
  CANVAS_POPOVER_CHIP_OPEN: "canvas_popover_chip_open",
  CANVAS_NODE_CONTENT_EDIT: "canvas_node_content_edit",
  CANVAS_LUT_IMPORT_CLICK: "canvas_lut_import_click",
  CANVAS_LUT_IMPORT_SUCCESS: "canvas_lut_import_success",
  CANVAS_LUT_IMPORT_FAILED: "canvas_lut_import_failed",
  // Chat — model picker (proposal theme 3)
  CHAT_MODEL_CHANGE: "chat_model_change",
  // Dialog (proposal theme 4 — generic dialog funnel)
  DIALOG_OPEN: "dialog_open",
  DIALOG_CLOSE: "dialog_close",
  DIALOG_STEP_CHANGE: "dialog_step_change",
  DIALOG_VALIDATION_ERROR: "dialog_validation_error",
  // Home (proposal theme 5) — input / attachment / popovers / tutorial / promo
  HOME_INPUT_FOCUS: "home_input_focus",
  HOME_INPUT_SUBMIT: "home_input_submit",
  HOME_INPUT_STOP: "home_input_stop",
  HOME_INPUT_CLEAR: "home_input_clear",
  HOME_ATTACHMENT_PICKER_OPEN: "home_attachment_picker_open",
  HOME_ATTACHMENT_ADD: "home_attachment_add",
  HOME_ATTACHMENT_REMOVE: "home_attachment_remove",
  HOME_SKILLS_POPOVER_OPEN: "home_skills_popover_open",
  HOME_MENTION_POPOVER_OPEN: "home_mention_popover_open",
  HOME_MODEL_PICKER_OPEN: "home_model_picker_open",
  HOME_MODEL_SELECTION_CHANGE: "home_model_selection_change",
  HOME_WORKSPACE_FOLDER_ACTION: "home_workspace_folder_action",
  HOME_TUTORIAL_CLICK: "home_tutorial_click",
  HOME_PROMOTION_SHOW: "home_promotion_show",
  HOME_PROMOTION_CLICK: "home_promotion_click",
  HOME_NAV_CLICK: "home_nav_click",
  // Built-in browser
  BROWSER_SURFACE_ACTION: "browser_surface_action",
  BROWSER_INSPIRATION_ACTION: "browser_inspiration_action",
  BROWSER_TAB_ACTION: "browser_tab_action",
  BROWSER_ADDRESS_SUBMIT: "browser_address_submit",
  BROWSER_BOOKMARK_ACTION: "browser_bookmark_action",
  BROWSER_TOOLBAR_ACTION: "browser_toolbar_action",
  BROWSER_NAVIGATION: "browser_navigation",
  BROWSER_REFERENCE_ACTION: "browser_reference_action",
  BROWSER_CAPTURE_RESULT: "browser_capture_result",
  BROWSER_ANNOTATION_ACTION: "browser_annotation_action",
  BROWSER_DOWNLOAD_START: "browser_download_start",
  BROWSER_DOWNLOAD_RESULT: "browser_download_result",
  BROWSER_DOWNLOAD_ACTION: "browser_download_action",
  BROWSER_PROFILE_IMPORT_ACTION: "browser_profile_import_action",
  // Credits details
  CREDIT_DETAILS_ACTION: "credit_details_action",
  // Settings navigation / memory management
  SETTINGS_SECTION_VIEW: "settings_section_view",
  MEMORY_MANAGEMENT_ACTION: "memory_management_action",
  // Topbar (proposal theme 5)
  TOPBAR_HOME_CLICK: "topbar_home_click",
  TOPBAR_SEARCH_OPEN: "topbar_search_open",
  GLOBAL_SEARCH_QUERY: "global_search_query",
  GLOBAL_SEARCH_RESULT_CLICK: "global_search_result_click",
  GLOBAL_SEARCH_COMMAND_EXECUTE: "global_search_command_execute",
  GLOBAL_SEARCH_NO_RESULT: "global_search_no_result",
  GLOBAL_SEARCH_CLOSE: "global_search_close",
  TOPBAR_TAB_ACTION: "topbar_tab_action",
  TOPBAR_TAB_CONTEXT_MENU_SELECT: "topbar_tab_context_menu_select",
  TOPBAR_NEW_WORKSPACE_CLICK: "topbar_new_workspace_click",
  WORKSPACE_OPEN_SUBMIT: "workspace_open_submit",
  // User menu (proposal theme 5)
  USER_MENU_OPEN: "user_menu_open",
  USER_MENU_ACTION: "user_menu_action",
  // Asset center
  ASSET_CREATE: "asset_create",
  ASSET_USE: "asset_use",
  ASSET_MATERIALIZE: "asset_materialize",
  ASSET_UNMATERIALIZE: "asset_unmaterialize",
  ASSET_PANEL_ACTION: "asset_panel_action",
  ASSET_CENTER_ACTION: "asset_center_action",
  ASSET_CENTER_SEARCH: "asset_center_search",
  ASSET_CENTER_FILTER: "asset_center_filter",
  ASSET_CENTER_SORT_CHANGE: "asset_center_sort_change",
  ASSET_CENTER_VIEW_CHANGE: "asset_center_view_change",
  ASSET_CREATE_FORM_ACTION: "asset_create_form_action",
  ASSET_EDIT_FORM_ACTION: "asset_edit_form_action",
  ASSET_EXPORT: "asset_export",
  ASSET_DETAIL_VIEW: "asset_detail_view",
  ASSET_DELETE: "asset_delete",
  ASSET_MATERIALIZE_DIALOG: "asset_materialize_dialog",
  ASSET_PROMOTE_VALIDATION_FAILED: "asset_promote_validation_failed",
  // IM bridge (Feishu / WeChat / Telegram → agent)
  IM_BRIDGE_OPEN: "im_bridge_open",
  IM_BRIDGE_ACCOUNT_ACTION: "im_bridge_account_action",
  IM_MESSAGE_SEND: "im_message_send",
  IM_MESSAGE_FAILED: "im_message_failed",
  // Page view (auto)
  PAGE_VIEW: "$pageview",
};
